# Generated by Django 4.1 on 2024-01-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upform',
            old_name='image',
            new_name='image2',
        ),
        migrations.RemoveField(
            model_name='upform',
            name='body',
        ),
        migrations.RemoveField(
            model_name='upform',
            name='title',
        ),
    ]
